spring:
  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:14500/eca?createDatabaseIfNotExist=true
    username: root
    password: sachi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8002

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost