spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:wfTtNr6CeInrvGv0P2wbpL7CFpzOwtjcNecOTrwYCDAl3kzj@a26b7f04-ccd4-449c-b1d2-bed4a12be561.asia-southeast1.firestore.goog:443/db-project?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}